### ISSUE TITLE
CalculateTaskScore.cpp runs way too slow

### ISSUE THREAD

**Issue by alanbarrett** [TheRosettaFoundation/SOLAS-Match-Backend#37]
CalculateTaskScore.cpp runs way too slow.

I have previously stopped succeeding invocations from proceeding until previous invocations have completed. This resolved any serious issues temporarily. However it was only a workaround.

The simplest approach is to move the addition of the number of days a Task has been unclaimed outside the loop. This will mean that normally Task Scores will not change so the optimisation that checks to see if a database update of the score to the very big UserTaskScores table is needed will nearly always avoid an update (and that update is VERY expensive as currently configured and dominates the time).

Instead of the continually changing of the score, I will add the number of days to the score in the database procedure getUserTopTasks() in the sort clause (ORDER by score).

```
Alan.
```

**Comment by spaceindaver** [comment]
Hey Alan,

Not sure if it is being done at the moment but you should check if the UserTasksScores table is cleaned of any archived/Completed tasks. Reducing the size of the table will increase access times and reduce memory overhead. If it doesn't do it currently you could add a new automated task to the backend that periodically removes irrelevant tasks. Another approach would be to add multiple new columns to the UserTasksScores table that splits the score into components that can each be updated in a different backend task that runs on its own schedule. For example, you could have an age_score column that is updated by a task that runs once or twice per day and only updates the that column. That way you don't take a hit when calling getUserTopTasks() and, if the rules that determine the score based on age change, it will be easier to update the algorithm that calculates it.

Just some ideas, hope it helps :-)

Dave

**Comment by alanbarrett** [comment]
Thanks Dave (@spaceindaver) for tracking this and for the input, it is helpful.

There is a Trigger "AFTER UPDATE ON `Tasks`" which removes UserTaskScores rows for completed tasks (so removing them from the large table).

I did consider adding another table which had an "age_score" for each task (but it is very fast to generate dynamically).

When investigating and testing this, I noticed that the score for an old Task (which is not yet done of which we have quite a few e.g. Mongolian or Uzbek) rises indefinitely. It turns out after adding a value of 800 an old "Uzbek" task will actually score higher that a task for which a translator actually has a matching language skill (Vietnamese in the case I am looking at). So I am proposing to limit the score addition for an old task to 700. Who originally designed the scoring algorithm? I would like to pass this modification past whomever that was?

```
Alan.
```

**Comment by reinhardschaler** [comment]
Just a short note to say thank you for keeping SOLAS/Trommons not just alive but constantly making it better! - Haven’t been involved for some time, and it’s hard to let go, at least for some time, but it’s in excellent hands!

Reinhard

**Comment by alanbarrett** [comment]
This is now implemented and has reduced the update time (triggered each hour) from 16 hours (approx) to 16 minutes (approx). So it is now running every hour.
So we will be generating less heat and CO2!
See Commits:
https://github.com/TheRosettaFoundation/SOLAS-Match-Backend/commit/9d2ba9978e47c522fd86400603c31515514f35ac
https://github.com/TheRosettaFoundation/SOLAS-Match/commit/94a080523c98d8c06cbe59ea4c2a4e476bc9c85c

There may be further optimisations which could be done at a later time.

```
Alan.
```

**Comment by spaceindaver** [comment]
Hey Alan,

Sorry for the delay, that sounds like a really reasonable change to the algorithm. When we wrote the algorithm at first we intended to alter it after gaining more insight into how people actually use the platform. Stuff like limiting the days and modifying weights and the like was exactly what we had in mind, as well as extending it with new properties as they became relevant :-)

Dave
