### ISSUE TITLE
As more Users and Tasks are added, CalculateTaskScore is beginning to take longer

### ISSUE THREAD

**Issue by alanbarrett** [TheRosettaFoundation/SOLAS-Match-Backend#41]
As more Users and Tasks are added, CalculateTaskScore is beginning to take longer (close to an hour now on average). So it looks as if the factor of 60 improvement is not enough (see https://github.com/TheRosettaFoundation/SOLAS-Match-Backend/issues/37 ).

```
Alan.
```

**Comment by alanbarrett** [comment]
These two commits address this...
https://github.com/TheRosettaFoundation/SOLAS-Match/commit/ce6724ca50cd68eb1898156fd942237bdb5dddcf
https://github.com/TheRosettaFoundation/SOLAS-Match-Backend/commit/0130685a93246d8f6f82ac44041cd039c1879cd0

This removes the background CalculateTaskScore (UserTaskScores) calculation completely and replaces it with an ORDER BY clause in the MySQL procedure getUserTopTasks().

This has the advantage that the Task Score calculation is always up to date, reflecting any newly added tasks immediately (there were issues with a NULL suppressing tasks that should have been displayed).

Additionally the new getUserTopTasks() (and getUserTopTasksCount()) is currently 2.5 times faster than the old one (because it does not have to join a huge table).

The new score calculation takes 6 lines of SQL and is in some ways easier to understand and update.

```
Alan.
```

**Comment by alanbarrett** [comment]
This was also required: https://github.com/TheRosettaFoundation/SOLAS-Match/commit/b82d3317d1aa885c221bc0464825c6cf9f903678

```
Alan.
```

**Comment by reinhardschaler** [comment]
Thanks for all this really brilliant work, Alan - without it, Trommons (and with it The Rosetta Foundation) would long have disappeared…

Reinhard
