### ISSUE TITLE
An error has occurred in the SOLAS-Match worker Daemon

### ISSUE THREAD

**Issue by alanbarrett** [TheRosettaFoundation/SOLAS-Match-Backend#44]
An error has occurred in the SOLAS-Match worker Daemon.
Failed to generate UserTaskStream email: Unable to find relevant data in the Database. Searched for User with ID 657 and their notification data.

This (or similar) seems to happen about 4 times a year...

[16/11/2016 01:10:00:353] Debug: MySQLHandler: Failed to connect to database:  "Lost connection to MySQL server at 'reading initial communication packet', system error: 9 QMYSQL: Unable to connect"
[16/11/2016 01:10:00:354] Debug: MySQLHandler::call - Initialization failed

    Alan.

**Comment by alanbarrett** [comment]
Another case...

EmailGenerator: Generating Project Created Email
MySQLHandler: Failed to connect to database:  "Lost connection to MySQL server at 'sending authentication information', system error: 9 QMYSQL: Unable to connect"
MySQLHandler::call - Initialization failed
Deleting MySQLHandler  "{418c89f1-5766-46df-9fee-73d8c615539e}"
[24/11/2016 13:47:10:842] Debug: Getting message from queue

Recipients:  ("paulina.abzieher@therosettafoundation.org", "asanka.wasala@ul.ie", "solas.user1@gmail.com", "alanabarrett0@gmail.com", "stefania.tringali@therosettafoundation.org")
Sender:  "info@trommons.org"
Subject:  "An error has occurred"
"<p>Hello,</p><p>An error has occurred in the SOLAS-Match worker Daemon. Project created generation failed. Unable to find  project with id 5823</p>"

Mail ( 12577 ) sent successfully

Restarted backend, not sure what to do to debug this.

    Alan.

**Comment by aquilax** [comment]
I've seen this happen before but in Python application. Not sure what a solution would be though. Re-connection probably. 
A side question, What does the backend do besides sending emails ?

**Comment by alanbarrett** [comment]
So should we look at coding a reconnection?

The backend used to do much more but see: https://github.com/TheRosettaFoundation/SOLAS-Match-Backend/issues/41

The Backend does not just send emails as requested by the frontend, it also does scheduled tasks (which are mostly email related): https://github.com/TheRosettaFoundation/SOLAS-Match-Backend/blob/master/schedule.xml

The backend unpublishes tasks here: https://github.com/TheRosettaFoundation/SOLAS-Match-Backend/blob/master/CorePlugin/TaskJobs/DeadlineChecker.cpp#L77

@Paulina-Rosetta why do we unpublish tasks?

Maybe before coding a reconnection we should review the functions of the backend.

    Alan.

**Comment by aquilax** [comment]
My thinking is more in the lines of, aren't the backend and the queue an overkill in this instance?
Long running processes can be done even in PHP, and queuing  for small volumes can be done in Redis or even the database.

**Comment by alanbarrett** [comment]
I agree about overkill... Maybe I should review what the backend does.

    Alan.

**Comment by alanbarrett** [comment]
Here is a summary of what the backend does, it is quite complicated the way everything is scheduled, but I think I have got (mostly) everything...

>> On a timed basis the following classes are run...
A) DeadlineChecker (Sends notifications emails and unpublises tasks)
B) TaskStreamNotificationHandler (Send notifications of relevant tasks to subscribed users)
C) StatisticsUpdate (updates statistics)

>> These classes are run on request from the front end...
A) CalculateProjectDeadlines
B) OrgCreatedNotifications
C) SendTaskUploadNotifications
D) TaskRevokedNotificationHandler

>> The backend sends the following emails...
BannedLoginGenerator
ClaimedTaskSourceUpdatedGenerator
ClaimedTaskUploadedGenerator
EmailVerificationGenerator
NewImageUploadedEmailGenerator
OrgCreate_SiteAdmin
OrgCreated_OrgEmail
OrgDeadlinePassedMailGenerator
OrgFeedbackGenerator
OrgMembershipAcceptedGenerator
OrgMembershipRefusedEmailGenerator
OrgTaskRevokedGenerator
PasswordResetEmailGenerator
ProjectCreatedGenerator
ProjectImageApprovedEmailGenerator
ProjectImageDisapprovedEmailGenerator
ProjectImageRemovedEmailGenerator
TaskArchivedEmailGenerator
TaskClaimedEmailGenerator
TaskScoreEmailGenerator
TrackedTaskUploadedEmailGenerator
UserBadgeAwardedGenerator
UserClaimedTaskEarlyWarningDeadlinePassedEmailGenerator
UserClaimedTaskLateWarningDeadlinePassedEmailGenerator
UserFeedbackGenerator
UserReferenceEmailGenerator
UserTaskClaimEmailGenerator
UserTaskDeadlineEmailGenerator
UserTaskRevokedGenerator
UserTaskStreamEmailGenerator

    Alan.

**Comment by spaceindaver** [comment]
Hey @alanbarrett 
The idea behind unpublishing tasks was to ensure people did not translate a file that was no longer needed by the organisation. If a task has passed its deadline then it is safe to assume the translation is no longer relevant for the organisation so we unpublish it. This ensures the people don't waste their time with translations that will never be used instead of providing a translation for a different task that is more relevant.

Hope that helps :-)

P.S. I wrote 90% of the C++ backend so if you need clarification on anything feel free to give me a shout!

Dave

**Comment by alanbarrett** [comment]
@spaceindaver 
Thanks for the offer to help. We may call on that if we get stuck.

The reason I asked about the unpublish is that, in practice, quite often what happens is that @Paulina-Rosetta pushes out the deadline rather than let it be unpublished because the organisation still wants the work done. So that is why I am asking @Paulina-Rosetta what should we be doing, should we unpublish or not... I will have a discussion with her about possibly changing the process (or maybe it is fine as it is).

By the way, some time ago I added extra notification emails to the process as the deadline is reached to avoid @Paulina-Rosetta manually sending out reminders to someone who has claimed a task. We need to try and remove as much manual intervention as possible and we have made a number of changes to Trommons to do this.

As far core problem in this issue, I will look at adding code to do a reconnection when we get these errors. Have you seen those errors with MySQL before?

    Alan.

**Comment by spaceindaver** [comment]
Yeah, I remember seeing it before alright, can't really remember what caused it. It might have been related to there being too many simultaneous connections to the MySQL DB. It might be fine just reopening the connection but maybe a small delay might help the system calm down a bit.

Also, something I meant to do before I left was to turn off all the logging from the backend. It spends a lot of time printing those logs so there would probably be a significant speedup in disabling them. Not sure if you have done this already.

**Comment by Paulina-Rosetta** [comment]
@alanbarrett Re unpublishing, I don't think it's useful to automaticaly unpublish asks once the deadline passes. In the vast majority of cases, there is some flexibility with the deadline. 

We sometimes unpublish tasks when we don't want them to be publically visible for some reason - even though anyone with the link can still access them when unpublished. 

As soon as we become aware that a task is no longer needed, we delete it from the system. Tasks that end up unpublished because of an expired deadline usually end up being updated and published by us manually to make them available again.

@stefania91 Did I miss anything?

**Comment by alanbarrett** [comment]
See Commit 2ee2f771fadcb3f5b6814407fab52cf4d78c2c96

Hopefully this reconnection will solve these occasional issues.

@aquilax , @Paulina-Rosetta , @spaceindaver 

    Alan.
