### ISSUE TITLE
Review Unpublishing

### ISSUE THREAD

**Issue by alanbarrett** [TheRosettaFoundation/SOLAS-Match-Backend#45]
See: https://github.com/TheRosettaFoundation/SOLAS-Match-Backend/issues/44

@Paulina-Rosetta  said...
Re unpublishing, I don't think it's useful to automatically unpublish tasks once the deadline passes. In the vast majority of cases, there is some flexibility with the deadline.

We sometimes unpublish tasks when we don't want them to be publically visible for some reason - even though anyone with the link can still access them when unpublished.

As soon as we become aware that a task is no longer needed, we delete it from the system. Tasks that end up unpublished because of an expired deadline usually end up being updated and published by us manually to make them available again.

@stefania91  Did I miss anything?

**Comment by alanbarrett** [comment]
@Paulina-Rosetta @stefania91 

Commit 75e6175c9b6fff8844855c16f49ef54a863cef92 removes the code to unpublish.
So all tasks will now be left published at their deadline.

    Alan.

**Comment by alanbarrett** [comment]
@stefania91 wrote...
Hi Alan,

I don't know if I'd better create an issue about this, but I noticed that I keep receiving emails once or maybe twice a day for each expired task. That's pretty annoying but the problem is that some volunteers have complained about this as well, so apparently I'm not the only one having this problem: is there something you could do?

Thank you and have a good day
... My response...
Maybe this is a side effect of the change I made, see: https://github.com/TheRosettaFoundation/SOLAS-Match-Backend/issues/45

I will check into this when I get a chance.

    Alan.

**Comment by alanbarrett** [comment]
@stefania91  ,

In the past we un-published tasks that reached their deadline. But on 8th December we stopped doing that. I probably did not think deeply enough about this (although I did spend quite a lot of time thinking about it, but obviously not enough!).

So currently a Task which is:
- Passed its deadline and
- Not Completed and
- Is (still) Published

Will send an email every day to the translator and a different one to anyone who is subscribed to the task.

People who are subscribed to the task are (more or less)...
- The user who created the project and left "Track Project:" checked when the project was created,
- Anyone who otherwise explicitly tracked the Project or Task,
- and Paulina because (autofollow_admin_ids=1012).

But I am not sure why @stefania91 is getting these emails (would you have tracked the project?).

But could you forward me an example of the email to make sure I am looking at the right one.

So we need to decide with @Paulina-Rosetta  what we need to do.

Options without too much thought are...
- Un-publish the task as before.
- Stop the reminders after one or more days have passed.
- Leave as is (possibly manually changing the deadline).
... What do we want to happen?

We should discuss when you have thought about this.

    Alan.

**Comment by stefania91** [comment]
Thanks Alan! I do track projects actually. Isn't there a way to send those reminders only on the first and second day and maybe, let's say, four days after the task has expired? Because usually, we contact ourselves the volunteers who haven't submitted the task yet, so I guess it's a bit too many emails for them.

**Comment by Paulina-Rosetta** [comment]
If I'm unstanding correctly, we are sending reminder emails every day about every task that has passed its deadline? Correct? That does seem like overkill...

For tasks where the deadline has expired, and they haven't been claimed, one email to whoever has tracked the task should be enough. This will remind us/orgs that the deadline needs to be updated (or the task deleted).

For tasks that have been claimed, I think we decided to send one reminder a week before the deadline and another one a week after the deadline has passed? See #1202 
That would seem sufficient to me.

I think ending the automatic unpublishing certainly helped in that volunteers now claim tasks after they have expired. We still have to manually change deadlines on these tasks, but it means that tasks which we might have overlooked after they ended up unpublished, and never updated, now get claimed.

**Comment by alanbarrett** [comment]
@stefania91 and @Paulina-Rosetta ,

I will go with "For tasks where the deadline has expired, and they haven't been claimed, one email to whoever has tracked the task should be enough".

This will be straightforward enough to do and should stop email overload.

By the way, I confirm, the emails we are discussing here are in addition to the reminders send to translators (only) one week before and one week after the deadline that @Paulina-Rosetta  mentions.

@stefania91 ,
Do you want to be set to be automatically tracking Projects and Tasks? It seems you are probably doing it manually at present.

    Alan.

**Comment by stefania91** [comment]
@alanbarrett 
I think your solution for the unclaimed tasks is the best option: we usually update them straight away, so one reminder is enough. 

I am tracking projects manually at the moment, but I prefer to keep it that way, because it's easier for me to see if there's some project that I still need to add to the report.

**Comment by alanbarrett** [comment]
@Paulina-Rosetta @stefania91 

I said I would implement "For tasks where the deadline has expired, and they haven't been claimed, one email to whoever has tracked the task should be enough".

In fact I did slightly different in that the fix applies (as the current code does) whether or not the tasks have been claimed,
as the notification on deadline expiration is sent to all those who have been tracking the task
(additionally, if the task has been claimed, the volunteer/translator also gets the notification).

The one week before and one week after emails still go out to the volunteer/translator.

This is fixed by a change to database SQL (notifications are only sent once for a task reaching its deadline within the previous 24 hours.

See https://github.com/TheRosettaFoundation/SOLAS-Match/commit/d12e72d3295c53548fa2332db027c015660a107b

    Alan.
