### ISSUE TITLE
Create organisation button

### ISSUE THREAD

**Issue by stefania91** [TheRosettaFoundation/SOLAS-Match-Backend#47]
We just realised that the "Create organisation"button has disappeared from all the non-admin profiles.

For example, @Paulina-Rosetta can see it from her admin account, but not from her volunteer standard account.

The one in the screenshot is a profile of an organisation who is just registered as a volunteer because they can't go any further.

Thanks! 
Stefania
![create organisation button](https://cloud.githubusercontent.com/assets/22887100/22058699/c9a3758c-dd61-11e6-8248-2050722e8913.png)

**Comment by alanbarrett** [comment]
The user has an issue (ideally we should do a usability review)... but we think there is not a software problem.

    Alan.
