### ISSUE TITLE
Removing JavaScript from outgoing emails

### ISSUE THREAD

**Issue by alanbarrett** [TheRosettaFoundation/SOLAS-Match-Backend#50]
@aquilax  and others,

In looking at another issue, I noticed that we do not clean JavaScript from outgoing emails.
JavaScript could appear in an email because of injected script tags in User names, Project Names, Task Names, Badges, Feedback and some others (see full list below).
We do not clean this (as we do for display on the Trommons website to avoid XSS).

It seems most email readers (e.g. GMail) suppress this from display in any case, so it might not be a big issue.

I am currently not working on changing this. Any suggestions on whether we should worry about this?

    Alan.

List...
BannedLoginGenerator.cpp(39): dict.SetValue("USERNAME", user->display_name());
BannedLoginGenerator.cpp(60): commentDict->SetValue("COMMENT", banData->comment());
ClaimedTaskSourceUpdatedGenerator.cpp(36): dict.SetValue("USERNAME", user->display_name());
ClaimedTaskSourceUpdatedGenerator.cpp(38): dict.SetValue("TASK_TITLE", task->title());
ClaimedTaskUploadedGenerator.cpp(49): dict.SetValue("USERNAME", user->display_name());
ClaimedTaskUploadedGenerator.cpp(51): dict.SetValue("TASK_TITLE", task->title());
NewImageUploadedEmailGenerator.cpp(48): dict.SetValue("PROJECT_TITLE", project->title());
OrgCreated_OrgEmail.cpp(33): dict.SetValue("USERNAME", admin->display_name());
OrgCreated_SiteAdmin.cpp(32): dict.SetValue("USERNAME", admin->display_name());
OrgDeadlinePassedEmailGenerator.cpp(39): dict.SetValue("USERNAME", user->display_name());
OrgDeadlinePassedEmailGenerator.cpp(43): dict.SetValue("TASK_TITLE", task->title());
OrgFeedbackGenerator.cpp(55): dict.SetValue("USERNAME", claimant->display_name());
OrgFeedbackGenerator.cpp(59): dict.SetValue("TASKTITLE", task->title());
OrgFeedbackGenerator.cpp(60): dict.SetValue("FEEDBACK", feedback.toStdString());
OrgMembershipAcceptedGenerator.cpp(59): dict.SetValue("USERNAME", user->display_name());
OrgMembershipRefusedEmailGenerator.cpp(37): dict.SetValue("USERNAME", user->display_name());
OrgTaskRevokedGenerator.cpp(32): dict.SetValue("USERNAME", user->display_name());
OrgTaskRevokedGenerator.cpp(33): dict.SetValue("TASK_TITLE", task->title());
OrgTaskRevokedGenerator.cpp(38): dict.SetValue("CLAIMANT_NAME", claimant->display_name());
PasswordResetEmailGenerator.cpp(45): dict.SetValue("USERNAME", user->display_name());
ProjectCreatedGenerator.cpp(44): dict.SetValue("PROJECT_TITLE", project->title());
ProjectImageApprovedEmailGenerator.cpp(54): dict.SetValue("PROJECT_TITLE", project->title());
ProjectImageApprovedEmailGenerator.cpp(58): dict.SetValue("USERNAME", user->display_name());
ProjectImageDisapprovedEmailGenerator.cpp(54): dict.SetValue("PROJECT_TITLE", project->title());
ProjectImageDisapprovedEmailGenerator.cpp(58): dict.SetValue("USERNAME", user->display_name());
ProjectImageRemovedEmailGenerator.cpp(48): dict.SetValue("PROJECT_TITLE", project->title());
TaskArchivedEmailGenerator.cpp(52): dict.SetValue("USERNAME", user->display_name());
TaskArchivedEmailGenerator.cpp(56): dict.SetValue("TASK_TITLE", task->title());
TaskClaimedEmailGenerator.cpp(40): dict.SetValue("USERNAME", user->display_name());
TaskClaimedEmailGenerator.cpp(44): dict.SetValue("TASK_TITLE", task->title());
TaskClaimedEmailGenerator.cpp(45): dict.SetValue("TRANSLATOR_NAME", translator->display_name());
TrackedTaskUploadedEmailGenerator.cpp(54): dict.SetValue("USERNAME", user->display_name());
TrackedTaskUploadedEmailGenerator.cpp(55): dict.SetValue("TRANSLATOR_NAME", translator->display_name());
TrackedTaskUploadedEmailGenerator.cpp(56): dict.SetValue("TASK_TITLE", task->title());
UserBadgeAwardedGenerator.cpp(76): dict.SetValue("USERNAME", user->display_name());
UserBadgeAwardedGenerator.cpp(77): dict.SetValue("BADGE_NAME", badge_title.toStdString());
UserClaimedTaskEarlyWarningDeadlinePassedEmailGenerator.cpp(38): dict.SetValue("USERNAME", user->display_name());
UserClaimedTaskEarlyWarningDeadlinePassedEmailGenerator.cpp(42): dict.SetValue("TASK_TITLE", task->title());
UserClaimedTaskLateWarningDeadlinePassedEmailGenerator.cpp(38): dict.SetValue("USERNAME", user->display_name());
UserClaimedTaskLateWarningDeadlinePassedEmailGenerator.cpp(42): dict.SetValue("TASK_TITLE", task->title());
UserFeedbackGenerator.cpp(57): dict.SetValue("USERNAME", user->display_name());
UserFeedbackGenerator.cpp(58): dict.SetValue("FEEDBACK", feedback.toStdString());
UserFeedbackGenerator.cpp(62): dict.SetValue("TASK_TITLE", task->title());
UserFeedbackGenerator.cpp(64): dict.SetValue("CLAIMANT_NAME", claimant->display_name());
UserReferenceEmailGenerator.cpp(39): dict.SetValue("DISPLAY_NAME", displayName);
UserReferenceEmailGenerator.cpp(54): taskSect->SetValue("TASK_TITLE", task->title());
UserReferenceEmailGenerator.cpp(103): taskSect->SetValue("TASK_TITLE", task->title());
UserTaskClaimEmailGenerator.cpp(37): dict.SetValue("USERNAME", user->display_name());
UserTaskClaimEmailGenerator.cpp(46): dict.SetValue("TASK_TITLE", task->title());
UserTaskDeadlineEmailGenerator.cpp(38): dict.SetValue("USERNAME", user->display_name());
UserTaskDeadlineEmailGenerator.cpp(42): dict.SetValue("TASK_TITLE", task->title());
UserTaskRevokedGenerator.cpp(30): dict.SetValue("USERNAME", user->display_name());
UserTaskRevokedGenerator.cpp(32): dict.SetValue("TASK_TITLE", task->title());
UserTaskStreamEmailGenerator.cpp(68): taskSect->SetValue("TASK_TITLE", task->title());
UserTaskStreamEmailGenerator.cpp(102): tagsList->SetValue("TAG_DETAILS", tagDetails.toStdString());
UserTaskStreamEmailGenerator.cpp(103): tagsList->SetValue("TAG_LABEL", tag->label());
UserTaskStreamEmailGenerator.cpp(120): taskSect->SetValue("PROJECT_TITLE", project->title());

**Comment by aquilax** [comment]
@alanbarrett It is a valid threat and while the major email clients will sanitize the content, there is no such guarantee for all.
Ideally the template engine should support safe strings, if it is aware that the produced content is HTML but probably that's not the case.

**Comment by alanbarrett** [comment]
OK I will add a fix. We use "ctemplate", I should probably verify it does not sanitise the output before adding the fix.

    Alan.

**Comment by alanbarrett** [comment]
Note:

These two should not be filtered, because first is a URL (with legal "<>")  and second is entered by site admin whom we trust.

UserTaskStreamEmailGenerator.cpp(102): tagsList->SetValue("TAG_DETAILS", tagDetails.toStdString());

BannedLoginGenerator.cpp(60): commentDict->SetValue("COMMENT", banData->comment());

    Alan.

**Comment by alanbarrett** [comment]
This is addressed by commit 5ad207c0b310b3db05e6a00f77ef2624b1f07fbc
It seems to be working, I will check some other emails as they come out just to be sure.

    Alan.
